---
- hosts: localhost
  become: yes

  tasks:
    - name: Install main set of packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - clang
          - clanag-analyzer
          - clang-tools-extra
          - gcc
          - git
          - git-email
          - git-lfs
          - gitk
          - jq
          - lshw
          - lua
          - luarocks
          - lutris
          - make
          - mc
          - mutt
          - neovim
          - nmap
          - podman
          - postfix
          - powertop
          - pre-commit
          - python3-neovim
          - python3-pip
          - rclone
          - rubypick
          - shellcheck
          - shfmt
          - sqlite
          - tio
          - tmux
          - wireshark
          - usbutils
          - vim
          - vlc
          - yq
          - yt-dlp
          - zsh
    - name: Install packages required for Yocto
      ansible.builtin.dnf:
        name: "{{ yocto_packages }}"
        state: present
      vars:
        yocto_packages:
          - bzip2
          - ccache
          - chrpath
          - cpio
          - cpp
          - diffstat
          - diffutils
          - file
          - findutils
          - gawk
          - gcc
          - gcc-c++
          - git
          - glibc-devel
          - glibc-langpack-en
          - glibc-locale-source
          - gzip
          - hostname
          - latexmk
          - libacl
          - librsvg2-tools
          - lz4
          - make
          - patch
          - perl
          - perl-bignum
          - perl-Data-Dumper
          - perl-File-Compare
          - perl-File-Copy
          - perl-FindBin
          - perl-locale
          - perl-Text-ParseWords
          - perl-Thread-Queue
          - python
          - python3
          - python3-GitPython
          - python3-jinja2
          - python3-pexpect
          - python3-pip
          - python3-pyyaml
          - python3-sphinx
          - rpcgen
          - socat
          - tar
          - texinfo
          - texlive-collection-fontsextra
          - texlive-collection-fontsrecommended
          - texlive-collection-latex
          - texlive-collection-latexextra
          - texlive-collection-latexrecommended
          - texlive-collection-xetex
          - texlive-fncychap
          - texlive-gnu-freefont
          - texlive-tex-gyre
          - texlive-xetex
          - unzip
          - wget
          - which
          - xz
          - zstd
