---
- hosts: localhost
  become: yes

  tasks:
    - name: Install main set of packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ansible
          - audacity
          - autoconf
          - automake
          - bless
          - bzip2
          - ccache
          - chrpath
          - clang
          - clang-analyzer
          - clang-tools-extra
          - cmake
          - codespell
          - cpio
          - cpp
          - cppcheck
          - diffstat
          - diffutils
          - dtc
          - file
          - findutils
          - firefox
          - fuse-sshfs
          - gawk
          - gcc
          - gcc-c++
          - gimp
          - git
          - git-email
          - git-lfs
          - gitk
          - glibc-devel
          - glibc-langpack-en
          - glibc-locale-source
          - gnome-tweaks
          - gzip
          - hostname
          - inkscape
          - jq
          - latexmk
          - libacl
          - librsvg2-tools
          - lshw
          - lua
          - luarocks
          - lutris
          - lz4
          - make
          - mc
          - meson
          - mutt
          - ncdu
          - neovim
          - nmap
          - okular
          - oxipng
          - patch
          - perl
          - perl-bignum
          - perl-Data-Dumper
          - perl-File-Compare
          - perl-File-Copy
          - perl-FindBin
          - perl-locale
          - perl-Text-ParseWords
          - perl-Thread-Queue
          - php-cli
          - podman
          - postfix
          - powertop
          - pre-commit
          - pulseview
          - python
          - python3
          - python3-GitPython
          - python3-jinja2
          - python3-neovim
          - python3-pexpect
          - python3-pip
          - python3-pyyaml
          - python3-sphinx
          - rclone
          - ripgrep
          - rpcgen
          - rubypick
          - shellcheck
          - shfmt
          - socat
          - sqlite
          - strace
          - tar
          - texinfo
          - texlive-collection-fontsextra
          - texlive-collection-fontsrecommended
          - texlive-collection-latex
          - texlive-collection-latexextra
          - texlive-collection-latexrecommended
          - texlive-collection-xetex
          - texlive-fncychap
          - texlive-gnu-freefont
          - texlive-tex-gyre
          - texlive-xetex
          - tio
          - tmux
          - unzip
          - usbutils
          - vim
          - vlc
          - wget
          - which
          - wireshark
          - xz
          - yq
          - yt-dlp
          - zsh
          - zstd
    - name: Add the flathub flatpak repository remote
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: Install multiple packages
      community.general.flatpak:
        name:
          - com.github.tchx84.Flatseal
          - com.mojang.Minecraft
          - com.vscodium.codium
          - org.ghidra_sre.Ghidra
          - org.godotengine.Godot3Sharp
          - org.kicad.KiCad
          - org.musicbrainz.Picard
          - org.signal.Signal 
